docker:
  image: yegor256/java8
decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  pubring.gpg: "repo/.rultor/pubring.gpg.asc"
  secring.gpg: "repo/.rultor/secring.gpg.asc"
install: |-
  java -version
deploy:
  script: |
    cat /home/r/script.sh
    bash .rultor/deploy.sh
